---
# tasks file for basic-setup
- name: Upgrade all packages
  apt:
    upgrade: yes
    autoclean: yes
    update_cache: true

- name: Install basic packages
  apt:
    name:
      - net-tools
      - curl
      - python3-pip
      - whois
    update_cache: true
    state: latest
