---
# playbook.yml

- name: Playbook for nginx-python-test
  hosts: home-node
  gather_facts: yes
  roles:
    - role: nginx-pci
      tags: 'nginx-pci'

    - role: basic-setup
      tags: 'basic-setup'

    - role: aws-ip-range
      tags: 'aws-ip-range'
